### ISSUE TITLE
Xử lý trường hợp ẩn, xử lý format đầu ra ẩn

### ISSUE THREAD

**Issue by letronghoangminh** [letronghoangminh/PBL1#5]
Xử lý lại format ẩn ra trong ex với 3 số thập phân ở đuôi
Lấy biến situation trả về từ file methods so sánh trường hợp nghiệm (cụ thể đã comment trong index)
Nếu được thì làm báo cáo lun hehe

**Comment by hoangnhan1203** [comment]
> Xử lý lại format ẩn ra trong ex với 3 số thập phân ở đuôi
> Lấy biến situation trả về từ file methods so sánh trường hợp nghiệm (cụ thể đã comment trong index)
> Nếu được thì làm báo cáo lun hehe

Đã in ra danh sách nghiệm (array ex[]) theo 3 situation và setprecision cho situation 2.
